version: '3.8'
services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: accountspayable
    ports:
      - "5432:5432:"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: accountspayable_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/accountspayable
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456

volumes:
  postgres_data:
  